server:
  port: 80

      
# log 日志等级：debug error warn info
# log.debug("调式信息") ===》system.out

# SpringBoot 如何实现自动化配置
# 1.pom.xml
#   SpringBoot 配置文件application*.yml
#   SpringBoot 默认指定了的常用版本
# 2.SpringBoot启动器
#   SpringBootApplication注解构成
#     @SpringBootConfiguration
#           @Configuration  SpringIOC容器注解配置注解==》beans.xml
#     @ComponentScan("com.yc.xxxx")
#           组件扫描：springboot 会自动扫描启动类所在包以及子包
#     @EnableAutoConfiguration
#           @AutoConfigurationPackage  自动配置包
#           @Import(AutoConfigurationImportSelector.class) 导入自动选择器
# 启动博客项目